### ISSUE TITLE
Complex conditions for Decision Tree

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/ai-act-decisiontree#34]
_Before picking up this ticket, please check with Guusje/Ravi whether the YAML file is ready!_ 

We need to find a way to save the history of answers given to the AI Act Decision Tree, as the next question often depends on the answer given to a previous question. In the decision tree.yaml file, this is indicated by if-statements, for example: 

nextQuestionId: '7.0'
            if: 1.8 == "Ja" && ( 1.0.2 == "Nee" || 1.0.3 == "Nee" ) 

In this example, we need to save the answers to questions 1.8, 1.0.2, and 1.0.3 to make sure the tree works. 

Laurens already made a start on this ticket using JEXL, see linked commit. 

Implementation notes:
- Get decision tree yaml from the github repo
- add redirect object into answer structure
 ```
    redirect: 
      - nextQuestionId: '3.0'
         if: 1.8 == "Ja" || 1.10 == "Ja"
      - nextQuestionId: '6.0'
         if: 1.10 == "Nee"
```
- use jexl to parse if statement
- We also want to keep the orginal object structure of answers
- Edit schema
